#!/usr/bin/env python3
"""Generate Rust IPC struct definitions from the schema snapshot.

Produces struct defs + encode/decode using inline expressions in vec![...].
"""

import json
import sys
from pathlib import Path

SNAPSHOT_PATH = Path(__file__).parent / "schema_snapshot.json"
OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent / "rust" / "sglang-server" / "src" / "schema"


def field_encode_expr(py_type, field_name):
    """Return an rmpv::Value expression. All fields are rmpv::Value, so just clone."""
    return f'self.{field_name}.clone()'


def field_decode_expr(py_type, field_name, idx):
    """Extract field by index. All fields are rmpv::Value, so just clone the value."""
    return f'arr.get({idx}).cloned().unwrap_or(rmpv::Value::Nil)'


def field_decode_type(py_type):
    """Return the Rust type for decode — uses rmpv::Value for opaque fields."""
    t = py_type.strip()
    if t in ("str", "Optional[str]", "int", "Optional[int]", "bool", "Optional[bool]",
             "bytes", "Optional[bytes]", "array", "Optional[array]",
             "Optional[List[str]]", "Optional[List[Optional[str]]]",
             "Optional[List[int]]", "String", "Option<String>"):
        return field_rust_type(t)
    if "SessionParams" in t:
        return "Option<crate::schema::SessionParams>"
        return field_rust_type(t)
    return "rmpv::Value"


def field_rust_type(py_type):
    """All fields are rmpv::Value in Phase 1 scaffolding."""
    return "rmpv::Value"


def field_decode_type(py_type):
    """All fields are rmpv::Value in Phase 1 scaffolding."""
    return "rmpv::Value"


def generate():
    snapshot = json.loads(SNAPSHOT_PATH.read_text())
    structs = snapshot["structs"]

    mod_path = OUTPUT_DIR / "mod.rs"

    # Structs to include (all msgspec.Struct subclasses, skip helper metrics)
    skip = {"MemoryMetrics", "SpeculativeMetrics", "LoRAMetrics",
            "DisaggregationMetrics", "QueueMetrics", "Function", "Tool",
            "BaseReq", "BaseBatchReq"}
    names = [n for n in structs
             if n not in skip and structs[n].get("tag") is True]

    lines = [
        "// Auto-generated. Do not edit.",
        "// Generated by tools/rust-tkm-migration/codegen_rust.py",
        "",
        "use crate::error::Error;",
        "",
        "#[derive(Debug, Clone)]",
        "pub struct SessionParams {",
        "    pub id: Option<String>,",
        "    pub rid: Option<String>,",
        "    pub offset: Option<i64>,",
        "    pub replace: Option<bool>,",
        "    pub drop_previous_output: Option<bool>,",
        "}",
        "",
        "impl SessionParams {",
        "    pub fn encode_value(&self) -> rmpv::Value {",
        "        use rmpv::Value;",
        "        let mut map = Vec::new();",
        "        if let Some(v) = &self.id { map.push((Value::from(\"id\"), Value::from(v.as_str()))); }",
        "        if let Some(v) = &self.rid { map.push((Value::from(\"rid\"), Value::from(v.as_str()))); }",
        "        if let Some(v) = self.offset { map.push((Value::from(\"offset\"), Value::from(v))); }",
        "        if let Some(v) = self.replace { map.push((Value::from(\"replace\"), Value::from(v))); }",
        "        if let Some(v) = self.drop_previous_output { map.push((Value::from(\"drop_previous_output\"), Value::from(v))); }",
        "        Value::Map(map)",
        "    }",
        "}",
        "",
    ]

    for name in names:
        sd = structs[name]
        fields = sd.get("resolved_fields", [])
        tag = sd.get("tag")
        need_decode = name in (
            "BatchStrOutput", "BatchTokenIDOutput", "BatchEmbeddingOutput",
            "TokenizedGenerateReqInput", "TokenizedEmbeddingReqInput",
            "AbortReq", "FlushCacheReqInput", "FlushCacheReqOutput",
            "ProfileReq",
        )

        # Struct definition — all fields rmpv::Value for now (Phase 1 scaffolding)
        lines.append(f"#[derive(Debug, Clone)]")
        lines.append(f"pub struct {name} {{")
        for f in fields:
            lines.append(f"    pub {f['name']}: rmpv::Value,")
        lines.append("}")
        lines.append("")

        # Encode for tagged structs (excluding base classes)
        if tag is True and name not in ("BaseReq", "BaseBatchReq"):
            lines.append(f"impl {name} {{")
            lines.append("    pub fn encode(&self) -> Result<Vec<u8>, Error> {")
            lines.append("        use rmpv::Value;")
            lines.append("        let arr = Value::Array(vec![")
            lines.append(f'            Value::from("{name}"),')
            for f in fields:
                expr = field_encode_expr(f["type"], f["name"])
                lines.append(f"            {expr},")
            lines.append("        ]);")
            lines.append("        let mut buf = Vec::new();")
            lines.append("        rmpv::encode::write_value(&mut buf, &arr)")
            lines.append("            .map_err(|e| Error::Codec(e.to_string()))?;")
            lines.append("        Ok(buf)")
            lines.append("    }")

            # Decode for critical structs
            if need_decode:
                expected_len = len(fields) + 1
                lines.append("")
                lines.append("    pub fn decode(data: &[u8]) -> Result<Self, Error> {")
                lines.append("        use rmpv::Value;")
                lines.append(f'        const TAG: &str = "{name}";')
                lines.append("        let val: Value = rmpv::decode::read_value(&mut &data[..])")
                lines.append("            .map_err(|e| Error::Codec(e.to_string()))?;")
                lines.append("        let arr = val.as_array()")
                lines.append("            .ok_or_else(|| Error::Codec(\"expected array\".to_string()))?;")
                lines.append("")
                lines.append("        // Validate tag (index 0)")
                lines.append("        let tag = arr.first()")
                lines.append("            .and_then(|v| v.as_str())")
                lines.append("            .ok_or_else(|| Error::Codec(\"missing tag\".to_string()))?;")
                lines.append(f'            if tag != TAG {{')
                lines.append(f'                return Err(Error::Codec(format!(')
                lines.append(f'                    "expected tag {{TAG}}, got {{tag}}")));')
                lines.append('            }')
                lines.append("")
                lines.append(f'        // Validate array length (expected {expected_len}: tag + {len(fields)} fields)')
                lines.append(f'        if arr.len() != {expected_len} {{')
                lines.append(f'            return Err(Error::Codec(format!("expected {expected_len} elements, got {{}}", arr.len())));')
                lines.append('        }')
                lines.append("")
                for i, f in enumerate(fields):
                    dexpr = field_decode_expr(f["type"], f["name"], i + 1)
                    rt = field_decode_type(f["type"])
                    lines.append(f"        let {f['name']}: {rt} = {dexpr};")
                lines.append("")
                lines.append("        Ok(Self {")
                for f in fields:
                    lines.append(f"            {f['name']},")
                lines.append("        })")
                lines.append("    }")

            lines.append("}")
            lines.append("")

    content = "\n".join(lines)
    mod_path.write_text(content)

    # Run rustfmt on generated code; fail hard if missing or broken
    import subprocess
    subprocess.run(["rustfmt", str(mod_path)], check=True)

    print(f"Wrote {mod_path} ({len(lines)} lines, {len(names)} structs)")


if __name__ == "__main__":
    generate()
